[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
[project]
name = "enigma-db"
version = "0.0.1"
authors = [
  { name="Xiao Chen", email="xiao.chen@databricks.com" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/xiaochen-db/enigma"
Issues = "https://github.com/xiaochen-db/enigma/issues"
